### ISSUE TITLE
wordlist

### ISSUE THREAD

**Issue by Wierdo-star** [bossiskar/seed-phrase-generator#11]
Hi,
how can I change wordlist only for 12 words? I know words to my wallet but I dont know their sequence. Yes I am asshole...
If I change "wordlist.h" it still uses all words and not only my 12.
Thank you very much

**Comment by Max1mk4** [comment]
anyway this software just generating random seedphrase without check. so its just for fun.

**Comment by bossiskar** [comment]
> Hi, how can I change wordlist only for 12 words? I know words to my wallet but I dont know their sequence. Yes I am asshole... If I change "wordlist.h" it still uses all words and not only my 12. Thank you very much

At the moment there is no such thing, I think I will add such a function in the near future
