### ISSUE TITLE
Question about balance

### ISSUE THREAD

**Issue by WilliamRiker2701** [bossiskar/seed-phrase-generator#2]
Hi, this program checks the balance in real time in the blockchain or checks it from an internal database?

**Comment by bossiskar** [comment]
Hi, the program checks the wallet balance through blockchain requests.

**Comment by LeopardosKing** [comment]
does running the program multible times help increase the speed of finding wallets with balance? or does it work like A-Z?
and does stoping the program and running again start the proccess with same seed order?

**Comment by bossiskar** [comment]
> does running the program multible times help increase the speed of finding wallets with balance? or does it work like A-Z? and does stoping the program and running again start the proccess with same seed order?

The program generates seed phrase randomly and then checks the wallet balance. Multiple runs can improve the wallets search, but the main role is played by the characteristic of your computer

**Comment by LeopardosKing** [comment]
Why does my anti virus show the file as trojan when running the .exe ? ESET anti virus

﻿
SeedGen.exe(8740);a variant of Win64/Spy.Agent.IN trojan ; contained infected files (after the next restart);;;CCBF70453AF92360BA139FE927DABE926DD0AEC7;

**Comment by bossiskar** [comment]
> Why does my anti virus show the file as trojan when running the .exe ? ESET anti virus
> 
> ﻿ SeedGen.exe(8740);a variant of Win64/Spy.Agent.IN trojan ; contained infected files (after the next restart);;;CCBF70453AF92360BA139FE927DABE926DD0AEC7;

It's a false positive. This is an open source program, anyone can look it up and compile it.
