### ISSUE TITLE
nice clone https://github.com/rezass1020/Seed-Phrase-Generator

### ISSUE THREAD

**Issue by goodcobra9folk** [bossiskar/seed-phrase-generator#7]
this fake use https://github.com/rezass1020/Seed-Phrase-Generator

**Comment by bossiskar** [comment]
facepalm

**Comment by WilliamRiker2701** [comment]
> this fake use https://github.com/rezass1020/Seed-Phrase-Generator

The code of your supposed original program is of such level of copy-paste that it literally points to bossiskar github. Nice try troll.

![image](https://github.com/bossiskar/seed-phrase-generator/assets/59099301/c2e23be4-5003-4182-8a3f-1f33a35f430d)
