### ISSUE TITLE
if i open the txt

### ISSUE THREAD

**Issue by Crash1802** [bossiskar/seed-phrase-generator#9]
Hey 
do I have to leave the txt file open so that it can write something into it or is it okay if it is closed?

**Comment by Crash1802** [comment]
and how long does it take until he finds a wallet?

**Comment by bossiskar** [comment]
> Hey do I have to leave the txt file open so that it can write something into it or is it okay if it is closed?

Hello, no need to open it

> and how long does it take until he finds a wallet?

Depends on luck
